AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: VisionMind Analyzer (SAM)

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket

  VisionMindFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: ./
      Events:
        AnalyzeApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
  BucketName:
    Value: !Ref UploadBucket
