AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for Exercise 1 (API + Lambda + DynamoDB)

Resources:
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: exercicio1-table-cfn
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        PostItems:
          Type: Api
          Properties:
            Path: /items
            Method: post
        GetItems:
          Type: Api
          Properties:
            Path: /items
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
