name: Exercicio 1 GCP Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação a ser executada (deploy ou delete)'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - delete

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install test dependencies
        working-directory: exercicios/exercicio1/gcp
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tests
        working-directory: exercicios/exercicio1/gcp
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest tests/

  deploy:
    name: Deploy to GCP
    needs: test
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SLS Dependencies
        working-directory: exercicios/exercicio1/gcp
        run: npm install

      - name: Serverless Deploy
        working-directory: exercicios/exercicio1/gcp
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: npx serverless deploy

  delete:
    name: Delete GCP Stack
    if: github.event.inputs.action == 'delete'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SLS Dependencies
        working-directory: exercicios/exercicio1/gcp
        run: npm install

      - name: Serverless Remove
        working-directory: exercicios/exercicio1/gcp
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: npx serverless remove
